CREATE DATABASE IF NOT EXISTS sistema_tutorias DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sistema_tutorias;

CREATE TABLE IF NOT EXISTS roles (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(50) NOT NULL UNIQUE);
INSERT INTO roles (id, nombre) VALUES (1, 'Administrador'), (2, 'Tutor'), (3, 'Estudiante') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre);

CREATE TABLE IF NOT EXISTS usuarios (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, id_rol INT NOT NULL, fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS carreras (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL, codigo VARCHAR(20) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS materias (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL, codigo VARCHAR(20) NOT NULL UNIQUE, id_carrera INT NOT NULL);
CREATE TABLE IF NOT EXISTS estudiantes (id INT AUTO_INCREMENT PRIMARY KEY, id_usuario INT NOT NULL UNIQUE, id_carrera INT NOT NULL, matricula VARCHAR(20) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS tutores (id INT AUTO_INCREMENT PRIMARY KEY, id_usuario INT NOT NULL UNIQUE, especialidad VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS tutor_materias (id INT AUTO_INCREMENT PRIMARY KEY, id_tutor INT NOT NULL, id_materia INT NOT NULL);
CREATE TABLE IF NOT EXISTS disponibilidad (id INT AUTO_INCREMENT PRIMARY KEY, id_tutor INT NOT NULL, dia_semana VARCHAR(15) NOT NULL, hora_inicio TIME NOT NULL, hora_fin TIME NOT NULL);
CREATE TABLE IF NOT EXISTS tutorias (id INT AUTO_INCREMENT PRIMARY KEY, id_estudiante INT NOT NULL, id_tutor INT NOT NULL, id_materia INT NOT NULL, fecha DATE NOT NULL, hora TIME NOT NULL, estado VARCHAR(20) DEFAULT 'Pendiente', tema VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS evaluaciones (id INT AUTO_INCREMENT PRIMARY KEY, id_tutoria INT NOT NULL UNIQUE, calificacion INT CHECK (calificacion BETWEEN 1 AND 5), comentario TEXT, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
